import type { BankQuestion } from './bank.js';

type Level = 'small' | 'medium' | 'big';
type Trio = { title: string; options: [string, string, string]; answer: 0 | 1 | 2 };

// 中秋知识题：简单 20、中等 20、难题 10。依据常见节俗与文献（酉阳杂俎、汉乐府、李商隐、北宋膳夫录等）。
const ITEMS: Array<{ level: Level; tag: string; zh: Trio; en: Trio; de: Trio }> = [
  // —— 简单 ——
  { level: 'small', tag: 'date',
    zh: { title: '中秋节是农历哪一天？', options: ['八月十五', '正月初一', '五月初五'], answer: 0 },
    en: { title: 'When is the Mid-Autumn Festival in the lunar calendar?', options: ['15th day of the 8th month', '1st day of the 1st month', '5th day of the 5th month'], answer: 0 },
    de: { title: 'Wann ist das Mondfest im Mondkalender?', options: ['15. Tag des 8. Monats', '1. Tag des 1. Monats', '5. Tag des 5. Monats'], answer: 0 } },
  { level: 'small', tag: 'reunion',
    zh: { title: '中秋节另一个很常见的名字是什么？', options: ['团圆节', '清明节', '端午节'], answer: 0 },
    en: { title: 'What is another common name for the Mid-Autumn Festival?', options: ['Reunion Festival', 'Tomb-Sweeping Day', 'Dragon Boat Festival'], answer: 0 },
    de: { title: 'Wie heißt das Mondfest noch oft?', options: ['Fest der Wiederbegegnung', 'Qingming-Fest', 'Drachenbootfest'], answer: 0 } },
  { level: 'small', tag: 'mooncake',
    zh: { title: '中秋节家家最常吃什么？', options: ['月饼', '粽子', '汤圆'], answer: 0 },
    en: { title: 'What do families most often eat at Mid-Autumn?', options: ['Mooncakes', 'Zongzi', 'Tangyuan'], answer: 0 },
    de: { title: 'Was essen die Familien beim Mondfest am häufigsten?', options: ['Mondkuchen', 'Zongzi', 'Tangyuan'], answer: 0 } },
  { level: 'small', tag: 'moon',
    zh: { title: '中秋夜里大家最爱看什么？', options: ['又圆又亮的月亮', '日出', '下雪'], answer: 0 },
    en: { title: 'What do people love to watch on Mid-Autumn night?', options: ['The round bright moon', 'Sunrise', 'Snowfall'], answer: 0 },
    de: { title: 'Was schauen die Leute in der Mondfestnacht gern an?', options: ['Den runden hellen Mond', 'Den Sonnenaufgang', 'Schneefall'], answer: 0 } },
  { level: 'small', tag: 'chang-e',
    zh: { title: '传说里嫦娥住在哪里？', options: ['月亮上', '海底', '森林里'], answer: 0 },
    en: { title: 'Where does Chang-e live in the story?', options: ['On the moon', 'Under the sea', 'In a forest'], answer: 0 },
    de: { title: 'Wo wohnt Chang-e in der Sage?', options: ['Auf dem Mond', 'Unter dem Meer', 'Im Wald'], answer: 0 } },
  { level: 'small', tag: 'rabbit',
    zh: { title: '嫦娥身边的小动物是谁？', options: ['玉兔', '老虎', '熊猫'], answer: 0 },
    en: { title: 'Which little animal stays with Chang-e?', options: ['The jade rabbit', 'A tiger', 'A panda'], answer: 0 },
    de: { title: 'Welches kleine Tier bleibt bei Chang-e?', options: ['Der Jadehase', 'Ein Tiger', 'Ein Panda'], answer: 0 } },
  { level: 'small', tag: 'wugang',
    zh: { title: '传说谁在月亮上砍桂树？', options: ['吴刚', '后羿', '孙悟空'], answer: 0 },
    en: { title: 'Who is said to chop the osmanthus tree on the moon?', options: ['Wu Gang', 'Hou Yi', 'Sun Wukong'], answer: 0 },
    de: { title: 'Wer hackt der Sage nach den Osmanthusbaum auf dem Mond?', options: ['Wu Gang', 'Hou Yi', 'Sun Wukong'], answer: 0 } },
  { level: 'small', tag: 'osmanthus',
    zh: { title: '中秋前后最常开的花是什么？', options: ['桂花', '梅花', '荷花'], answer: 0 },
    en: { title: 'Which flower often blooms around Mid-Autumn?', options: ['Osmanthus', 'Plum blossom', 'Lotus'], answer: 0 },
    de: { title: 'Welche Blume blüht oft um das Mondfest?', options: ['Osmanthus', 'Pflaumenblüte', 'Lotus'], answer: 0 } },
  { level: 'small', tag: 'lantern',
    zh: { title: '写在灯笼上让人猜的小题目叫什么？', options: ['灯谜', '口算', '口令'], answer: 0 },
    en: { title: 'What are the little puzzles written on lanterns called?', options: ['Lantern riddles', 'Mental math', 'Passwords'], answer: 0 },
    de: { title: 'Wie heißen die kleinen Rätsel auf den Laternen?', options: ['Laternenrätsel', 'Kopfrechnen', 'Kennwörter'], answer: 0 } },
  { level: 'small', tag: 'mooncake',
    zh: { title: '月饼为什么常常做成圆形？', options: ['像圆月，表示团圆', '方便装进书包', '像一个方盒子'], answer: 0 },
    en: { title: 'Why are mooncakes often round?', options: ['Like the full moon, for reunion', 'To fit in a schoolbag', 'Like a square box'], answer: 0 },
    de: { title: 'Warum sind Mondkuchen oft rund?', options: ['Wie der Vollmond, für die Wiederbegegnung', 'Damit sie in die Schultasche passen', 'Wie eine eckige Schachtel'], answer: 0 } },
  { level: 'small', tag: 'reunion',
    zh: { title: '中秋节最想做的事是什么？', options: ['和家人聚在一起', '一个人出远门', '整天睡觉'], answer: 0 },
    en: { title: 'What do people most want to do at Mid-Autumn?', options: ['Gather with family', 'Travel alone far away', 'Sleep all day'], answer: 0 },
    de: { title: 'Was möchten die Leute am Mondfest am liebsten?', options: ['Mit der Familie zusammenkommen', 'Ganz allein weit wegfahren', 'Den ganzen Tag schlafen'], answer: 0 } },
  { level: 'small', tag: 'houyi',
    zh: { title: '传说里后羿的妻子是谁？', options: ['嫦娥', '织女', '白素贞'], answer: 0 },
    en: { title: 'Who is Hou Yi’s wife in the story?', options: ['Chang-e', 'Zhinü the weaver', 'Bai Suzhen'], answer: 0 },
    de: { title: 'Wer ist in der Sage die Frau von Hou Yi?', options: ['Chang-e', 'Die Weberin Zhinü', 'Bai Suzhen'], answer: 0 } },
  { level: 'small', tag: 'rabbit',
    zh: { title: '玉兔在月亮上常常做什么？', options: ['捣药', '游泳', '踢足球'], answer: 0 },
    en: { title: 'What does the jade rabbit often do on the moon?', options: ['Pound medicine', 'Swim', 'Play football'], answer: 0 },
    de: { title: 'Was macht der Jadehase auf dem Mond oft?', options: ['Er stampft Medizin', 'Er schwimmt', 'Er spielt Fußball'], answer: 0 } },
  { level: 'small', tag: 'name',
    zh: { title: '北京人常把中秋节叫做什么？', options: ['八月节', '腊八节', '重阳节'], answer: 0 },
    en: { title: 'What do people in Beijing often call the Mid-Autumn Festival?', options: ['Eighth-Month Festival', 'Laba Festival', 'Double Ninth Festival'], answer: 0 },
    de: { title: 'Wie nennen viele Menschen in Peking das Mondfest?', options: ['Fest des achten Monats', 'Laba-Fest', 'Doppeltes-Neun-Fest'], answer: 0 } },
  { level: 'small', tag: 'offering',
    zh: { title: '赏月时桌上常摆什么？', options: ['月饼和新鲜水果', '只放书包', '雪人'], answer: 0 },
    en: { title: 'What is often set out while watching the moon?', options: ['Mooncakes and fresh fruit', 'Only a schoolbag', 'A snowman'], answer: 0 },
    de: { title: 'Was steht oft auf dem Tisch, wenn man den Mond anschaut?', options: ['Mondkuchen und frisches Obst', 'Nur eine Schultasche', 'Ein Schneemann'], answer: 0 } },
  { level: 'small', tag: 'lantern',
    zh: { title: '小朋友过中秋时常提着什么走？', options: ['灯笼', '雨伞当帽子', '大石头'], answer: 0 },
    en: { title: 'What do children often carry at Mid-Autumn?', options: ['Lanterns', 'An umbrella as a hat', 'A big stone'], answer: 0 },
    de: { title: 'Was tragen Kinder am Mondfest oft?', options: ['Laternen', 'Einen Schirm als Hut', 'Einen großen Stein'], answer: 0 } },
  { level: 'small', tag: 'moon',
    zh: { title: '圆圆的月亮在中秋象征什么？', options: ['团圆', '分开', '冬天结束'], answer: 0 },
    en: { title: 'What does the round moon stand for at Mid-Autumn?', options: ['Reunion', 'Being apart', 'The end of winter'], answer: 0 },
    de: { title: 'Wofür steht der runde Mond am Mondfest?', options: ['Wiederbegegnung', 'Getrenntsein', 'Das Ende des Winters'], answer: 0 } },
  { level: 'small', tag: 'name',
    zh: { title: '“仲秋”的“仲”是什么意思？', options: ['排在中间', '最小的', '最后一名'], answer: 0 },
    en: { title: 'What does “zhong” in “Zhongqiu” (Mid-Autumn) mean?', options: ['In the middle', 'The smallest', 'The last place'], answer: 0 },
    de: { title: 'Was bedeutet „zhong“ in „Zhongqiu“ (Mitte des Herbstes)?', options: ['In der Mitte', 'Der kleinste', 'Der letzte Platz'], answer: 0 } },
  { level: 'small', tag: 'osmanthus',
    zh: { title: '桂花常常做成哪样小吃？', options: ['桂花糕', '冰淇淋山', '汉堡'], answer: 0 },
    en: { title: 'Osmanthus is often made into which snack?', options: ['Osmanthus cake', 'A mountain of ice cream', 'A hamburger'], answer: 0 },
    de: { title: 'Woraus macht man Osmanthus oft?', options: ['Osmanthuskuchen', 'Einem Berg Eis', 'Einem Hamburger'], answer: 0 } },
  { level: 'small', tag: 'moon',
    zh: { title: '中秋晚上的月亮通常是什么样？', options: ['又圆又亮', '完全看不见', '方方的'], answer: 0 },
    en: { title: 'What does the moon usually look like on Mid-Autumn night?', options: ['Round and bright', 'Completely invisible', 'Square'], answer: 0 },
    de: { title: 'Wie sieht der Mond in der Mondfestnacht meist aus?', options: ['Rund und hell', 'Ganz unsichtbar', 'Eckig'], answer: 0 } },

  // —— 中等 ——
  { level: 'medium', tag: 'chang-e',
    zh: { title: '嫦娥最早的名字是什么？', options: ['姮娥', '西王母', '织女'], answer: 0 },
    en: { title: 'What was Chang-e’s earlier name?', options: ['Heng-e', 'Queen Mother of the West', 'The weaver maid'], answer: 0 },
    de: { title: 'Wie hieß Chang-e früher?', options: ['Heng-e', 'Königinmutter des Westens', 'Die Weberin'], answer: 0 } },
  { level: 'medium', tag: 'chang-e',
    zh: { title: '姮娥为什么改叫嫦娥？', options: ['避开汉文帝刘恒的名讳', '因为她喜欢唱歌', '因为她住在长江边'], answer: 0 },
    en: { title: 'Why was Heng-e renamed Chang-e?', options: ['To avoid Emperor Wen of Han’s personal name, Liu Heng', 'Because she liked singing', 'Because she lived by the Yangtze'], answer: 0 },
    de: { title: 'Warum wurde Heng-e in Chang-e umbenannt?', options: ['Wegen des Namensverbots für Kaiser Wen, Liu Heng', 'Weil sie gern sang', 'Weil sie am Jangtse wohnte'], answer: 0 } },
  { level: 'medium', tag: 'wugang',
    zh: { title: '吴刚砍桂写得最具体的是哪本书？', options: ['《酉阳杂俎》', '《三字经》', '《弟子规》'], answer: 0 },
    en: { title: 'Which book tells Wu Gang’s tree-chopping most clearly?', options: ['Youyang Zazu', 'Three Character Classic', 'Standards for Students'], answer: 0 },
    de: { title: 'Welches Buch erzählt Wu Gangs Baumfällen am genauesten?', options: ['Youyang Zazu', 'Dreizeichenklassiker', 'Regeln für Schüler'], answer: 0 } },
  { level: 'medium', tag: 'wugang',
    zh: { title: '传说里月中桂树有多高？', options: ['五百丈', '五寸', '只有一个人那么高'], answer: 0 },
    en: { title: 'How tall is the moon’s osmanthus tree in the story?', options: ['Five hundred zhang', 'Five cun', 'Only as tall as a person'], answer: 0 },
    de: { title: 'Wie hoch ist der Osmanthusbaum auf dem Mond in der Sage?', options: ['Fünfhundert Zhang', 'Fünf Cun', 'Nur so hoch wie ein Mensch'], answer: 0 } },
  { level: 'medium', tag: 'wugang',
    zh: { title: '吴刚是哪里人？', options: ['西河', '东海边上', '南山顶上'], answer: 0 },
    en: { title: 'Where was Wu Gang from?', options: ['Xihe', 'The eastern seashore', 'The top of South Mountain'], answer: 0 },
    de: { title: 'Woher kam Wu Gang?', options: ['Xihe', 'Vom Ostseestrand', 'Vom Gipfel des Südbergs'], answer: 0 } },
  { level: 'medium', tag: 'wugang',
    zh: { title: '吴刚为什么要不停地砍树？', options: ['学仙犯了错，被罚砍树', '他的工作是木匠', '树是他自己种的'], answer: 0 },
    en: { title: 'Why must Wu Gang keep chopping?', options: ['He was punished for a fault while learning to be an immortal', 'He works as a carpenter', 'He planted the tree himself'], answer: 0 },
    de: { title: 'Warum muss Wu Gang immer weiter hacken?', options: ['Er wurde für einen Fehler beim Unsterblichkeitslernen bestraft', 'Er arbeitet als Zimmermann', 'Er hat den Baum selbst gepflanzt'], answer: 0 } },
  { level: 'medium', tag: 'wugang',
    zh: { title: '桂树被砍开以后会怎样？', options: ['伤口马上又合上', '树马上倒下', '树变成石头'], answer: 0 },
    en: { title: 'What happens after the osmanthus tree is cut?', options: ['The cut closes at once', 'The tree falls at once', 'The tree turns to stone'], answer: 0 },
    de: { title: 'Was passiert, nachdem der Osmanthusbaum gehauen wird?', options: ['Die Wunde schließt sich sofort', 'Der Baum fällt sofort', 'Der Baum wird zu Stein'], answer: 0 } },
  { level: 'medium', tag: 'poem',
    zh: { title: '“嫦娥应悔偷灵药”是谁写的？', options: ['李商隐', '李白', '杜甫'], answer: 0 },
    en: { title: 'Who wrote “Chang-e must regret stealing the elixir”?', options: ['Li Shangyin', 'Li Bai', 'Du Fu'], answer: 0 },
    de: { title: 'Wer schrieb „Chang-e bereut gewiss den Diebstahl des Elixiers“?', options: ['Li Shangyin', 'Li Bai', 'Du Fu'], answer: 0 } },
  { level: 'medium', tag: 'poem',
    zh: { title: '“嫦娥应悔偷灵药”的下一句是什么？', options: ['碧海青天夜夜心', '床前明月光', '春眠不觉晓'], answer: 0 },
    en: { title: 'What is the next line after “Chang-e must regret stealing the elixir”?', options: ['Blue sea, blue sky, a heart each night', 'Moonlight before my bed', 'Spring sleep, I miss the dawn'], answer: 0 },
    de: { title: 'Wie geht der Vers nach „Chang-e bereut den Diebstahl des Elixiers“ weiter?', options: ['Blaues Meer, blauer Himmel, Nacht für Nacht das Herz', 'Mondlicht vor meinem Bett', 'Frühlingsschlaf, den Morgen verpasst'], answer: 0 } },
  { level: 'medium', tag: 'mooncake',
    zh: { title: '“小饼如嚼月，中有酥和饴”说的是什么？', options: ['宋代的节令小饼（月饼）', '元宵汤圆', '端午粽子'], answer: 0 },
    en: { title: '“A little cake like chewing the moon, with crisp pastry and malt sugar” describes what?', options: ['A Song-dynasty festival cake (mooncake)', 'Tangyuan dumplings', 'Dragon-boat zongzi'], answer: 0 },
    de: { title: 'Was beschreibt „ein kleiner Kuchen wie der Mond, mit Mürbeteig und Malzzucker“?', options: ['Einen Festkuchen der Song-Zeit (Mondkuchen)', 'Tangyuan', 'Drachenboot-Zongzi'], answer: 0 } },
  { level: 'medium', tag: 'history',
    zh: { title: '中秋在民间特别盛行，是从哪个时期开始明显起来的？', options: ['宋代', '秦代才第一次过', '直到今天才出现'], answer: 0 },
    en: { title: 'When did Mid-Autumn become widely popular among ordinary people?', options: ['In the Song dynasty', 'It was first kept only in the Qin dynasty', 'It appeared only in our time'], answer: 0 },
    de: { title: 'Seit wann ist das Mondfest im Volk besonders verbreitet?', options: ['Seit der Song-Zeit', 'Erst in der Qin-Zeit zum ersten Mal', 'Erst in unserer Zeit'], answer: 0 } },
  { level: 'medium', tag: 'history',
    zh: { title: '到了明清，人们怎样看中秋？', options: ['重要性可以和春节相比', '只是普通的一天', '节日已经消失'], answer: 0 },
    en: { title: 'By the Ming and Qing dynasties, how was Mid-Autumn regarded?', options: ['As important as the Spring Festival', 'As an ordinary day', 'The festival had disappeared'], answer: 0 },
    de: { title: 'Wie sah man das Mondfest in Ming- und Qing-Zeit?', options: ['So wichtig wie das Frühlingsfest', 'Als einen gewöhnlichen Tag', 'Das Fest war verschwunden'], answer: 0 } },
  { level: 'medium', tag: 'rabbit',
    zh: { title: '老北京中秋用泥做的月亮兔子叫什么？', options: ['兔儿爷', '石狮子', '熊猫灯'], answer: 0 },
    en: { title: 'What is the clay moon-rabbit of old Beijing called?', options: ['Lord Rabbit (Tu’er Ye)', 'A stone lion', 'A panda lantern'], answer: 0 },
    de: { title: 'Wie heißt der Ton-Mondhase im alten Peking?', options: ['Hasenfürst (Tu’er Ye)', 'Ein Steinlöwe', 'Eine Panda-Laterne'], answer: 0 } },
  { level: 'medium', tag: 'bobing',
    zh: { title: '厦门中秋有什么特别的传统活动？', options: ['博饼', '赛龙舟', '滑雪'], answer: 0 },
    en: { title: 'What special Mid-Autumn custom is known in Xiamen?', options: ['Bobing (dice cake game)', 'Dragon-boat racing', 'Skiing'], answer: 0 },
    de: { title: 'Welcher besondere Brauch gehört in Xiamen zum Mondfest?', options: ['Bobing (Würfelspiel um Kuchen)', 'Drachenbootrennen', 'Skifahren'], answer: 0 } },
  { level: 'medium', tag: 'bobing',
    zh: { title: '厦门博饼今天属于什么？', options: ['国家级非物质文化遗产', '一种数学考试', '一种新出的手机游戏'], answer: 0 },
    en: { title: 'What is Xiamen bobing recognized as today?', options: ['A national intangible cultural heritage', 'A math exam', 'A new phone game'], answer: 0 },
    de: { title: 'Was ist Xiamens Bobing heute?', options: ['Nationales immaterielles Kulturerbe', 'Eine Matheprüfung', 'Ein neues Handyspiel'], answer: 0 } },
  { level: 'medium', tag: 'rabbit',
    zh: { title: '“玉兔捣药”最早见于哪里？', options: ['汉乐府《董逃行》', '今天的报纸', '英语课本'], answer: 0 },
    en: { title: 'Where is the jade rabbit pounding medicine first mentioned?', options: ['The Han ballad “Dong Tao Xing”', 'Today’s newspaper', 'An English textbook'], answer: 0 },
    de: { title: 'Wo wird der medizinestampfende Jadehase zuerst erwähnt?', options: ['Im Han-Yuefu „Dong Tao Xing“', 'In der Zeitung von heute', 'Im Englischbuch'], answer: 0 } },
  { level: 'medium', tag: 'poem',
    zh: { title: '“欲斫月中桂，持为寒者薪”是谁的诗？', options: ['李白', '王维', '白居易'], answer: 0 },
    en: { title: 'Who wrote “I would cut the cassia in the moon for firewood for the cold”?', options: ['Li Bai', 'Wang Wei', 'Bai Juyi'], answer: 0 },
    de: { title: 'Wer schrieb „Ich wollte den Zimtbaum im Mond als Brennholz für die Frierenden schlagen“?', options: ['Li Bai', 'Wang Wei', 'Bai Juyi'], answer: 0 } },
  { level: 'medium', tag: 'chang-e',
    zh: { title: '传说嫦娥吃下的仙药来自谁？', options: ['西王母', '灶王爷', '土地公'], answer: 0 },
    en: { title: 'In the story, who did Chang-e’s elixir come from?', options: ['The Queen Mother of the West', 'The Kitchen God', 'The Earth God'], answer: 0 },
    de: { title: 'Von wem stammt in der Sage Chang-es Elixier?', options: ['Von der Königinmutter des Westens', 'Vom Küchengott', 'Vom Erdgott'], answer: 0 } },
  { level: 'medium', tag: 'mooncake',
    zh: { title: '有个民间传说，月饼里夹过怎样的字条？', options: ['约好八月十五夜里一同行动', '明天去春游', '记得写作业'], answer: 0 },
    en: { title: 'In one folk tale, what kind of note was hidden in mooncakes?', options: ['A call to act together on the night of the 15th of the 8th month', 'A spring outing tomorrow', 'Remember the homework'], answer: 0 },
    de: { title: 'Was stand in einer Volkssage auf dem Zettel im Mondkuchen?', options: ['Ein Aufruf, in der Nacht des 15. des 8. Monats gemeinsam zu handeln', 'Morgen ein Frühlingsausflug', 'Denk an die Hausaufgaben'], answer: 0 } },
  { level: 'medium', tag: 'worship',
    zh: { title: '旧时少女拜月，常许什么愿？', options: ['模样像嫦娥一样美', '变成一棵大树', '天天考试'], answer: 0 },
    en: { title: 'What did girls often wish when they worshipped the moon?', options: ['To be as beautiful as Chang-e', 'To become a big tree', 'To have a test every day'], answer: 0 },
    de: { title: 'Was wünschten sich Mädchen oft beim Mondanbeten?', options: ['So schön zu sein wie Chang-e', 'Ein großer Baum zu werden', 'Jeden Tag eine Prüfung'], answer: 0 } },

  // —— 难题 ——
  { level: 'big', tag: 'wugang',
    zh: { title: '《酉阳杂俎》写月桂，是在哪一卷？', options: ['前集卷一《天咫》', '专门的食谱卷', '只有图画没有文字'], answer: 0 },
    en: { title: 'Where in Youyang Zazu is the moon cassia described?', options: ['Former collection, chapter 1, “Tianzhi”', 'A cookbook chapter', 'Only in a picture, with no words'], answer: 0 },
    de: { title: 'Wo beschreibt Youyang Zazu den Zimtbaum im Mond?', options: ['Vordere Sammlung, Band 1, „Tianzhi“', 'In einem Kochkapitel', 'Nur auf einem Bild ohne Text'], answer: 0 } },
  { level: 'big', tag: 'wugang',
    zh: { title: '段成式怎样写吴刚受罚？', options: ['学仙有过，谪令伐树', '封他做国王', '送他回西河度假'], answer: 0 },
    en: { title: 'How does Duan Chengshi describe Wu Gang’s punishment?', options: ['A fault in learning immortality, banished to chop the tree', 'He was made a king', 'He was sent home to Xihe on holiday'], answer: 0 },
    de: { title: 'Wie beschreibt Duan Chengshi Wu Gangs Strafe?', options: ['Fehler beim Unsterblichkeitslernen, verbannt zum Bäumefällen', 'Er wurde König', 'Er durfte in Xihe Urlaub machen'], answer: 0 } },
  { level: 'big', tag: 'chang-e',
    zh: { title: '早期记载里，嫦娥奔月后成了什么？', options: ['月精', '太阳', '北斗星'], answer: 0 },
    en: { title: 'In early records, what did Chang-e become after flying to the moon?', options: ['The spirit of the moon', 'The sun', 'The Big Dipper'], answer: 0 },
    de: { title: 'Was wurde Chang-e in frühen Texten nach dem Flug zum Mond?', options: ['Der Geist des Mondes', 'Die Sonne', 'Der Große Wagen'], answer: 0 } },
  { level: 'big', tag: 'chang-e',
    zh: { title: '有的古本说嫦娥在月中变成了什么来捣药？', options: ['蟾蜍', '金鱼', '蝴蝶'], answer: 0 },
    en: { title: 'In some old versions, what did Chang-e become on the moon to pound medicine?', options: ['A toad', 'A goldfish', 'A butterfly'], answer: 0 },
    de: { title: 'In manchen alten Fassungen wurde Chang-e auf dem Mond was, um Medizin zu stampfen?', options: ['Eine Kröte', 'Ein Goldfisch', 'Ein Schmetterling'], answer: 0 } },
  { level: 'big', tag: 'food',
    zh: { title: '北宋郑望《膳夫录》说开封中秋吃什么？', options: ['中秋玩月羹', '北京烤鸭', '火锅'], answer: 0 },
    en: { title: 'What does Zheng Wang’s Song cookbook Shanfu Lu say Kaifeng ate at Mid-Autumn?', options: ['Mid-Autumn moon-gazing stew', 'Peking duck', 'Hotpot'], answer: 0 },
    de: { title: 'Was aß Kaifeng laut Zheng Wangs Song-Kochbuch Shanfu Lu am Mondfest?', options: ['Mondschau-Eintopf zum Mittherbst', 'Pekingente', 'Hotpot'], answer: 0 } },
  { level: 'big', tag: 'opera',
    zh: { title: '1915年梅兰芳创排的第一出古装戏是哪一出？', options: ['《嫦娥奔月》', '《红楼梦》', '《西游记》'], answer: 0 },
    en: { title: 'What was the first ancient-costume play Mei Lanfang created in 1915?', options: ['Chang-e Flies to the Moon', 'Dream of the Red Chamber', 'Journey to the West'], answer: 0 },
    de: { title: 'Welches war 1915 Mei Lanfangs erstes Stück in alter Tracht?', options: ['Chang-e fliegt zum Mond', 'Der Traum der Roten Kammer', 'Die Reise nach dem Westen'], answer: 0 } },
  { level: 'big', tag: 'calendar',
    zh: { title: '农历八月为什么叫“仲秋”？', options: ['秋季的第二个月，正在秋天正中', '因为一年有八个中秋', '因为皇帝姓仲'], answer: 0 },
    en: { title: 'Why is the eighth lunar month called “mid-autumn” (zhongqiu)?', options: ['It is the second month of autumn, in the middle of the season', 'Because there are eight Mid-Autumns a year', 'Because an emperor’s surname was Zhong'], answer: 0 },
    de: { title: 'Warum heißt der achte Mondmonat „Mitte des Herbstes“?', options: ['Er ist der zweite Herbstmonat, mitten in der Jahreszeit', 'Weil es acht Mondfeste im Jahr gibt', 'Weil ein Kaiser Zhong hieß'], answer: 0 } },
  { level: 'big', tag: 'rabbit',
    zh: { title: '《董逃行》里，玉兔把药奉给谁？', options: ['陛下', '街上的商人', '来做客的小朋友'], answer: 0 },
    en: { title: 'In “Dong Tao Xing”, who does the jade rabbit offer the medicine to?', options: ['His Majesty', 'A merchant in the street', 'A child visiting'], answer: 0 },
    de: { title: 'Wem reicht der Jadehase die Medizin in „Dong Tao Xing“?', options: ['Seiner Majestät', 'Einem Händler auf der Straße', 'Einem Kind zu Besuch'], answer: 0 } },
  { level: 'big', tag: 'rabbit',
    zh: { title: '老北京中秋要祭的“长耳定光仙”是谁？', options: ['玉兔', '吴刚', '后羿'], answer: 0 },
    en: { title: 'Who is the “Long-Eared Immortal of Fixed Light” worshipped in old Beijing at Mid-Autumn?', options: ['The jade rabbit', 'Wu Gang', 'Hou Yi'], answer: 0 },
    de: { title: 'Wer ist der „Unsterbliche mit langen Ohren und festem Licht“, den man im alten Peking am Mondfest verehrte?', options: ['Der Jadehase', 'Wu Gang', 'Hou Yi'], answer: 0 } },
  { level: 'big', tag: 'osmanthus',
    zh: { title: '比吴刚故事更早，《淮南子》已经说到月亮里有什么？', options: ['桂树', '火车', '学堂'], answer: 0 },
    en: { title: 'Earlier than the Wu Gang story, what does Huainanzi already place in the moon?', options: ['A cassia tree', 'A train', 'A school'], answer: 0 },
    de: { title: 'Was nennt Huainanzi schon im Mond, noch vor der Wu-Gang-Geschichte?', options: ['Einen Zimtbaum', 'Einen Zug', 'Eine Schule'], answer: 0 } },
];

const PAY: Record<Level, { reward: number; penalty: number }> = {
  small: { reward: 10, penalty: 5 },
  medium: { reward: 15, penalty: 8 },
  big: { reward: 20, penalty: 10 },
};

export function midAutumnQuestions(): BankQuestion[] {
  const rows: BankQuestion[] = [];
  for (const item of ITEMS) {
    const pay = PAY[item.level];
    for (const [lang, text] of [['zh_CN', item.zh], ['en', item.en], ['de', item.de]] as const) {
      rows.push({
        kind: 'knowledge',
        lang,
        difficulty: item.level,
        title: text.title,
        options: [...text.options],
        answer: text.answer,
        tag: item.tag,
        reward: pay.reward,
        penalty: pay.penalty,
      });
    }
  }
  return rows;
}
